### ISSUE TITLE
Guide user to install theme as submodule

### ISSUE THREAD

**Issue by WordlessEcho** [eatradish/Seje#15]
Hexo recommends user to edit theme config by `theme_config`:
```yaml
theme_config:
  # ...
```

However, it encountered some problem in removing entries of `menu`. Because Hexo will deep merge config instead of replace config:
```
theme_config:
  menu:
    Home: /
```
Will still be this in Seje:
```
{
  "menu": {
    "Home": "/",
    "Archives": "/archives",
    // ...
}
```

Hexo recommends the config of theme should be comment that all:
```yaml
menu:
  Home: /
  # Archives: /archives
  # About: /about
  # RSS: /rss
  # Member: /member
```
